### ISSUE TITLE
Dojo is giving error after recent update.

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#588]
**Describe the bug**
Dojo stopped running once upgraded to 0.2.44. Tried uninstalling, reinstalling but same issue. 
**Expected behavior**

**Screenshots**![image](https://user-images.githubusercontent.com/54225190/139526646-927700ba-f25d-4e3c-99f2-ea512e7af1b4.jpeg)
**
**MyNode hardware (please complete the following information):**
 - Device: [Raspi4]
 - Version [e.g. 0.2.44]

**Comment by tehelsper** [comment]
After you reset docker because it went rogue, can you re-install Dojo and see if it improves? Dojo requires Docker working properly, so that was likely the cause.

**Comment by imacfan** [comment]
> After you reset docker because it went rogue, can you re-install Dojo and see if it improves? Dojo requires Docker working properly, so that was likely the cause.

yes, its fixed now

**Comment by GalDornik** [comment]
I have the same problem, I was with v2.45 and Dojo did not work, I went back to 2.44 and it still does not work.
I try to update the Dojo version and it doesn't work either.

**Comment by tehelsper** [comment]
There is another recent Dojo issue due to one of the dependent docker containers it uses. A recent change was just added to resolve and it will be in the next release.

**Comment by GalDornik** [comment]
> There is another recent Dojo issue due to one of the dependent docker containers it uses. A recent change was just added to resolve and it will be in the next release.

Great, is there a scheduled date for the review?

**Comment by tehelsper** [comment]
I hope by early next week to have something ready. For now, this may be a workaround. Run these commands and then do a re-install of Dojo.

```
sudo wget https://raw.githubusercontent.com/mynodebtc/mynode/master/rootfs/standard/usr/bin/mynode_docker_images.sh -O /usr/bin/mynode_docker_images.sh
sudo mynode-reboot
```

**Comment by EternStudent** [comment]
Hi, updated to 0.2.46. 

Dojo is still "error" and docker is "error". Also now Mempool is "error". The logs say "failed to start". On Dojo and Mempool the logs refer to docker issues. I've tried to restart and reinstall Dojo but it doesn't help. Web SSH is also red. 

I'm not skilled enough to read the logs and keep disabling and enabling and reinstalling different apps in the correct order if the solution is there. 

What to do? Or wait for another upgrade?

**Comment by EternStudent** [comment]
I finally found a reset button for docker. Now all is green.

**Comment by pookster45** [comment]
Same problems as above, Mempool and Dojo errors and will not run. Have reset docker and ran the command you provided above. Have updated 3 times now with same issues, since 0.2.44. I am now running 0.2.47 on a Raspi4.  Please advise. Thanks!

**Comment by tehelsper** [comment]
Can you check the logs for Dojo and mempool?

**Comment by pookster45** [comment]
So, after resetting Docker they both seem to work now. That's cool.  BUT now, under Dojo, I no longer have a "Node Admin Key" listed. It just says "myAdminKey" and I get 
Invalid API key" if I type that into the Dojo Maintenance Tool.  So I am now unable to log into my Dojo Maintenance Tool. How do I get the key back? Was this deleted when I reset Docker?  Thanks!

**Comment by tehelsper** [comment]
That means Dojo didn't initialize properly. Did anything else happen? Maybe try another Dojo re-install now that Docker is working?
