### ISSUE TITLE
LNDg doesn't fetch data from LND

### ISSUE THREAD

**Issue by tukac** [mynodebtc/mynode#656]
LNDg v1.0.5 on myNode 0.2.55 doesn't connect to LND data.

LNDg doesn't show LND channel data: no opened or closed channels are shown, no transactional history of any kind. As if LND never had any channels. It correctly recognises LND public ID and on-chain balance.

I have changed admin pass from default (bolt) to my LND pass. Restarted LNDg, no improvement.

There seem to be no LNDg error log in `/var/log` dir.

RPi4 8Gb, SSD 1Tb
myNode 0.2.55 64bit Premium
LNDg v1.0.5

**Comment by tehelsper** [comment]
Can you try running:

sudo journalctl -u lndg

That will show the log data.

**Comment by tukac** [comment]
Password change and LNDg restart log:

```
May 08 09:55:45 myNode lndg[12696]: [08/May/2022 07:55:45] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
May 08 09:55:45 myNode lndg[12696]: [08/May/2022 07:55:45] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
May 08 09:55:45 myNode lndg[12696]: [08/May/2022 07:55:45] "GET /lndg-admin/jsi18n/ HTTP/1.1" 200 3343
May 08 09:56:09 myNode lndg[12696]: [08/May/2022 07:56:09] "GET /lndg-admin/password_change/ HTTP/1.1" 200 4394
May 08 09:56:43 myNode lndg[12696]: [08/May/2022 07:56:43] "POST /lndg-admin/password_change/ HTTP/1.1" 302 0
May 08 09:56:43 myNode lndg[12696]: [08/May/2022 07:56:43] "GET /lndg-admin/password_change/done/ HTTP/1.1" 200 2916
May 08 09:56:50 myNode lndg[12696]: [08/May/2022 07:56:50] "GET / HTTP/1.1" 200 8332
May 08 09:56:58 myNode lndg[12696]: [08/May/2022 07:56:58] "GET / HTTP/1.1" 200 8332
May 08 10:04:39 myNode lndg[12696]: [08/May/2022 08:04:39] "GET / HTTP/1.1" 200 8332
May 08 10:05:12 myNode systemd[1]: Stopping LNDg...
May 08 10:05:12 myNode lndg[12696]: Performing system checks...
May 08 10:05:12 myNode lndg[12696]: System check identified no issues (0 silenced).
May 08 10:05:12 myNode lndg[12696]: May 07, 2022 - 16:19:51
May 08 10:05:12 myNode lndg[12696]: Django version 4.0.4, using settings 'lndg.settings'
May 08 10:05:12 myNode lndg[12696]: Starting development server at http://0.0.0.0:8889/
May 08 10:05:12 myNode lndg[12696]: Quit the server with CONTROL-C.
May 08 10:05:13 myNode systemd[1]: lndg.service: Succeeded.
May 08 10:05:13 myNode systemd[1]: Stopped LNDg.
May 08 10:05:13 myNode systemd[1]: Starting LNDg...
May 08 10:05:13 myNode lndg[996]: Checking if device is shutting down...
May 08 10:05:13 myNode lndg[996]: Not shutting down!
May 08 10:05:13 myNode systemd[1]: Started LNDg.
May 08 10:05:18 myNode lndg[999]: Watching for file changes with StatReloader
May 08 10:05:28 myNode lndg[999]: [08/May/2022 08:05:28] "GET / HTTP/1.1" 200 8332
May 08 10:10:03 myNode lndg[999]: [08/May/2022 08:10:03] "GET / HTTP/1.1" 200 8332
May 08 10:26:33 myNode lndg[999]: [08/May/2022 08:26:33] "GET / HTTP/1.1" 200 8332
May 08 11:37:08 myNode lndg[999]: [08/May/2022 09:37:08] "GET / HTTP/1.1" 200 8332
May 08 11:37:14 myNode lndg[999]: [08/May/2022 09:37:14] "GET / HTTP/1.1" 200 8332
May 08 12:39:51 myNode lndg[999]: [08/May/2022 10:39:51] "GET / HTTP/1.1" 200 8332
May 08 16:22:50 myNode lndg[999]: [08/May/2022 14:22:50] "GET / HTTP/1.1" 200 8332
```

**Comment by tehelsper** [comment]
I don't see any errors. Is anything shown in the LNDg's interface?

**Comment by tukac** [comment]
Hidden fields are correct. No error notices whatsoever.

![Screenshot](https://user-images.githubusercontent.com/45404964/167367145-429d9fe8-2adb-4901-9d63-5f853447be06.png)

**Comment by tukac** [comment]
Latest LNDg is v1.1.0, I could try that. How to customise to upgrade?

**Comment by tehelsper** [comment]
Edit the json file in /usr/share/mynode_apps/lndg/lndg.json and update the version number. Then reboot or click Settings -> Refresh Application Database.

**Comment by tukac** [comment]
I have upgraded to LNDg v1.1.1 but problem remains. Any ideas?

**Comment by ABAPRules** [comment]
Same Problem here before and after Upgrade to LNDg 1.1.1 in MyNode 0.2.55 on raspi4 64-bit

**Comment by tehelsper** [comment]
OK, I'll try upgrading to 1.1.1 and see what happens. I have been seeing channel info, but I did notice a recent rx payment was not found.

**Comment by tehelsper** [comment]
OK, I've updated LNDg and I'm seeing similar issues. The generic data seems fine which makes me think the connection to LND is fine and may be a LNDg issue. I'm not sure how basic LND data can work, but detailed channel info would be failing. I may have to investigate more.

**Comment by ABAPRules** [comment]
After checking and fixing Systemd Setup for Backend Refresh (https://github.com/cryptosharks131/lndg/blob/master/systemd.md) i probably found the next problem (-> Readonly Database...?!):

● jobs-lndg.service - Run Jobs For Lndg
   Loaded: loaded (/etc/systemd/system/jobs-lndg.service; static; vendor preset: enabled)
   Active: inactive (dead) since Sat 2022-05-14 17:55:13 CEST; 6s ago
  Process: 30265 ExecStart=/usr/bin/bash /home/admin/lndg/jobs.sh (code=exited, status=0/SUCCESS)
 Main PID: 30265 (code=exited, status=0/SUCCESS)

May 14 17:55:09 myNode systemd[1]: Started Run Jobs For Lndg.
May 14 17:55:12 myNode bash[30265]: Error processing background data: attempt to write a readonly database
May 14 17:55:13 myNode systemd[1]: jobs-lndg.service: Succeeded.

**Comment by tehelsper** [comment]
This log may have some insight as well - /opt/mynode/lndg/logs/supervisord.log

If I understood correctly, the systemd files should not be necessary because I was running with supervisord. I have found one issue there where it didn't have permission to launch the pid file. Re-installing now.

**Comment by tehelsper** [comment]
I think I figured it out - no need for systemd but there were some issues with supervisord paths and permissions that would make some scripts not run properly.

I released a beta with the fix and a few other things.

**Comment by tukac** [comment]
I have upgraded to `beta_05-14-22_1652585694` but problem remains the same.

**Comment by tehelsper** [comment]
Try re-installing lndg after the upgrade (especially if you were already running v1.1.1).

**Comment by tukac** [comment]
Uninstalling and installing LNDg v1.1.1 solved most of the problem! Only thing still not working seems to be routing history: LNDg shows 0 routing history on all of the channels. ThunderHub shows routing history correctly.

**Comment by tukac** [comment]
Few hours have passed after re-installing LNDg and rebooting of myNode. Now routing history is shown correctly. I am closing this issue.

Solution: install myNode beta_05-14-22_165258569, then re-install LNDg v1.1.1
